[package]
name = "rule-converter-napi"
version = "0.3.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
napi = { version = "3", default-features = false, features = ["napi4"] }
napi-derive = "3"
rule-converter = { path = "..", default-features = false, features = ["parallel", "http"] }

[build-dependencies]
napi-build = "2"
