/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AnyBufferResult {
  kind: 'rules' | 'db'
  outputs: Record<string, Uint8Array>
  info: Record<string, AnyOutputInfo>
  skipped: Array<SkippedRule>
}

export interface AnyConvertOptions {
  inputTarget?: 'mihomo' | 'general' | 'egern' | 'sing-box' | 'geoip' | 'geosite' | 'asn'
  inputFormat?: 'yaml' | 'mrs' | 'text' | 'json' | 'srs' | 'domainset' | 'ruleset' | 'ipset' | 'mmdb' | 'sing-db' | 'metadb' | 'dat' | 'sing-geosite'
  inputBehavior?: 'auto' | 'domain' | 'ip' | 'classical'
  outputTarget?: 'mihomo' | 'general' | 'egern' | 'sing-box' | 'geoip' | 'geosite' | 'asn'
  outputFormat?: 'mrs' | 'text' | 'yaml' | 'json' | 'srs' | 'domainset' | 'ruleset' | 'ipset' | 'mmdb' | 'sing-db' | 'metadb' | 'dat' | 'sing-geosite'
  outputBehavior?: 'auto' | 'domain' | 'ip' | 'classical'
  countries?: Array<string>
  codes?: Array<string>
  asns?: Array<number>
  split?: boolean
  country?: string
  code?: string
  asn?: number
}

export interface AnyOutputInfo {
  behavior?: string
  format: string
  count: number
}

export interface AnyStringResult {
  kind: 'rules' | 'db'
  outputs: Record<string, string>
  info: Record<string, AnyOutputInfo>
  skipped: Array<SkippedRule>
}

export interface DetectResult {
  kind: 'rules' | 'db'
  target: 'mihomo' | 'general' | 'egern' | 'sing-box' | 'geoip' | 'geosite' | 'asn'
  format: string
  behavior?: string
}

export declare function bufToBuf(input: Uint8Array, options?: AnyConvertOptions | undefined | null): AnyBufferResult

export declare function bufToStr(input: Uint8Array, options?: AnyConvertOptions | undefined | null): AnyStringResult

export declare function fileToBuf(input: string, options?: AnyConvertOptions | undefined | null): AnyBufferResult

export declare function fileToStr(input: string, options?: AnyConvertOptions | undefined | null): AnyStringResult

export declare function detectBuf(input: Uint8Array): DetectResult

export declare function detectStr(input: string): DetectResult

export declare function detectFile(input: string): DetectResult

export declare function listAsnNumbers(input: string): Array<number>

export declare function listAsnNumbersFromBuffer(input: Uint8Array): Array<number>

export declare function listGeoipCountries(input: string): Array<string>

export declare function listGeoipCountriesFromBuffer(input: Uint8Array): Array<string>

export declare function listGeoipDatCountries(input: string): Array<string>

export declare function listGeoipDatCountriesFromBuffer(input: Uint8Array): Array<string>

export declare function listGeositeCodes(input: string): Array<string>

export declare function listGeositeCodesFromBuffer(input: Uint8Array): Array<string>


export interface MatchOptions {
  inputTarget?: 'mihomo' | 'general' | 'egern' | 'sing-box' | 'geoip' | 'geosite' | 'asn'
  inputFormat?: 'yaml' | 'mrs' | 'text' | 'json' | 'srs' | 'domainset' | 'ruleset' | 'ipset' | 'dat' | 'sing-geosite' | 'mmdb' | 'sing-db' | 'metadb'
  inputBehavior?: 'auto' | 'domain' | 'ip' | 'classical'
}

export interface MatchRule {
  behavior: string
  rule: string
  source?: string
  entry?: string
  set?: string
}

export interface MatchResult {
  matched: boolean
  query: string
  kind: string
  rules: Array<MatchRule>
}

export interface SkippedRule {
  rule: string
  reason: string
}

export declare function strToBuf(input: string, options?: AnyConvertOptions | undefined | null): AnyBufferResult

export declare function strToStr(input: string, options?: AnyConvertOptions | undefined | null): AnyStringResult

export declare function matchBuf(input: Uint8Array, query: string, options?: MatchOptions | undefined | null): MatchResult

export declare function matchStr(input: string, query: string, options?: MatchOptions | undefined | null): MatchResult

export declare function matchFile(input: string, query: string, options?: MatchOptions | undefined | null): MatchResult
