/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ConvertBufferOutput {
  behavior: 'domain' | 'ip'
  count: number
  buffer: Uint8Array
}

export interface ConvertBufferResult {
  outputs: Array<ConvertBufferOutput>
  skipped: Array<SkippedRule>
}

export declare function convertFileToBuffer(input: string | string[], options?: ConvertOptions | undefined | null): ConvertBufferResult

export declare function convertFileToMrs(input: string | string[], options?: ConvertOptions | undefined | null): ConvertResult

export declare function convertFileToPath(input: string | string[], output: string, options?: ConvertOptions | undefined | null): WriteResult

export declare function convertFileToString(input: string | string[], options?: ConvertOptions | undefined | null): ConvertStringResult

export interface ConvertOptions {
  inputTarget?: 'mihomo' | 'general' | 'egern' | 'sing-box'
  inputFormat?: 'yaml' | 'mrs' | 'text' | 'json' | 'srs'
  inputBehavior?: 'auto' | 'domain' | 'ip' | 'classical'
  outputTarget?: 'mihomo' | 'general' | 'egern' | 'sing-box'
  outputFormat?: 'mrs' | 'text' | 'yaml' | 'json' | 'srs' | 'domainset' | 'ruleset' | 'ipset'
  outputBehavior?: 'auto' | 'domain' | 'ip' | 'classical'
}

export interface ConvertOutput {
  behavior: 'domain' | 'ip'
  count: number
  bytes: Uint8Array
}

export declare function convertPayloadStringToBuffer(payload: string, options?: ConvertOptions | undefined | null): ConvertBufferResult

export declare function convertPayloadStringToMrs(payload: string, options?: ConvertOptions | undefined | null): ConvertResult

export declare function convertPayloadStringToString(payload: string, options?: ConvertOptions | undefined | null): ConvertStringResult

export declare function convertPayloadToBuffer(payload: Uint8Array, options?: ConvertOptions | undefined | null): ConvertBufferResult

export declare function convertPayloadToMrs(payload: Uint8Array, options?: ConvertOptions | undefined | null): ConvertResult

export declare function convertPayloadToString(payload: Uint8Array, options?: ConvertOptions | undefined | null): ConvertStringResult

export interface ConvertResult {
  outputs: Array<ConvertOutput>
  skipped: Array<SkippedRule>
}

export interface ConvertStringOutput {
  behavior: 'domain' | 'ip'
  count: number
  text: string
}

export interface ConvertStringResult {
  outputs: Array<ConvertStringOutput>
  skipped: Array<SkippedRule>
}

export interface SkippedRule {
  rule: string
  reason: string
}

export interface WriteResult {
  outputs: Array<WrittenOutput>
  skipped: Array<SkippedRule>
}

export interface WrittenOutput {
  behavior: 'domain' | 'ip'
  count: number
  path: string
}
