/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function convertFileToMrs(input: string | string[], options?: ConvertOptions | undefined | null): ConvertResult

export declare function convertFileToPath(input: string | string[], output: string, options?: ConvertOptions | undefined | null): WriteResult

export type RuleTarget = 'mihomo' | 'general' | 'egern' | 'sing-box'
export type RuleFormat = 'mrs' | 'text' | 'yaml' | 'json' | 'srs' | 'domainset' | 'ruleset' | 'ipset'
export type InputBehavior = 'auto' | 'domain' | 'ip' | 'classical'
export type OutputBehavior = 'domain' | 'ip' | 'classical'

export interface ConvertOptions {
  inputTarget?: RuleTarget
  inputFormat?: RuleFormat
  inputBehavior?: InputBehavior
  outputTarget?: RuleTarget
  outputFormat?: RuleFormat
  outputBehavior?: OutputBehavior
}

export interface ConvertOutput {
  behavior: 'domain' | 'ip'
  count: number
  bytes: Uint8Array
}

export declare function convertPayloadStringToMrs(payload: string, options?: ConvertOptions | undefined | null): ConvertResult

export declare function convertPayloadToMrs(payload: Uint8Array, options?: ConvertOptions | undefined | null): ConvertResult

export interface ConvertResult {
  outputs: Array<ConvertOutput>
  skipped: Array<SkippedRule>
}

export interface SkippedRule {
  rule: string
  reason: string
}

export interface WriteResult {
  outputs: Array<WrittenOutput>
  skipped: Array<SkippedRule>
}

export interface WrittenOutput {
  behavior: 'domain' | 'ip'
  count: number
  path: string
}
