use std::collections::HashMap;
use std::path::Path;

use anyhow::{Result, bail};
use maxminddb_writer::paths::IpAddrWithMask;

use crate::codec::db::common::{
    for_each_cidr, new_database, parse_cidr_with_context, set_database_has_ipv6, write_database,
    write_database_to_memory,
};
use crate::codec::mihomo::mrs::RuleSetOutput;

use super::common::AsnRecordValue;

pub fn build_asn_mmdb_from_paths<P, I>(entries: I, output: impl AsRef<Path>) -> Result<usize>
where
    P: AsRef<Path>,
    I: IntoIterator<Item = (u32, P)>,
{
    let mut db = new_database(
        false,
        "GeoLite2-ASN",
        "ASN database generated by rule-converter",
    );
    let mut values = HashMap::new();
    let mut has_ipv6 = false;
    let mut count = 0usize;

    for (asn, path) in entries {
        if asn == 0 {
            bail!("ASN must be greater than 0");
        }
        let path = path.as_ref();
        count += for_each_cidr(path, |cidr| {
            has_ipv6 |= cidr.addr.is_ipv6();
            let data_ref = match values.get(&asn) {
                Some(data_ref) => *data_ref,
                None => {
                    let data_ref = db.insert_value(AsnRecordValue {
                        autonomous_system_number: asn,
                        autonomous_system_organization: "",
                    })?;
                    values.insert(asn, data_ref);
                    data_ref
                }
            };
            db.insert_node(cidr, data_ref);
            Ok(())
        })?;
    }

    if count == 0 {
        bail!("ASN input does not contain any CIDR records");
    }
    set_database_has_ipv6(&mut db, has_ipv6);
    write_database(db, output.as_ref())?;
    Ok(count)
}

pub fn build_asn_mmdb_from_rule_sets<I>(entries: I, output: impl AsRef<Path>) -> Result<usize>
where
    I: IntoIterator<Item = (u32, RuleSetOutput)>,
{
    let (count, db) = build_asn_mmdb_database_from_rule_sets(entries)?;
    write_database(db, output.as_ref())?;
    Ok(count)
}

pub fn build_asn_mmdb_from_rule_sets_to_bytes<I>(entries: I) -> Result<(usize, Vec<u8>)>
where
    I: IntoIterator<Item = (u32, RuleSetOutput)>,
{
    let (count, db) = build_asn_mmdb_database_from_rule_sets(entries)?;
    Ok((count, write_database_to_memory(db)?))
}

pub(super) fn build_asn_mmdb_database_from_rule_sets<I>(
    entries: I,
) -> Result<(usize, maxminddb_writer::Database)>
where
    I: IntoIterator<Item = (u32, RuleSetOutput)>,
{
    let mut db = new_database(
        false,
        "GeoLite2-ASN",
        "ASN database generated by rule-converter",
    );
    let mut values = HashMap::new();
    let mut has_ipv6 = false;
    let mut count = 0usize;

    for (asn, rules) in entries {
        if asn == 0 {
            bail!("ASN must be greater than 0");
        }
        let data_ref = match values.get(&asn) {
            Some(data_ref) => *data_ref,
            None => {
                let data_ref = db.insert_value(AsnRecordValue {
                    autonomous_system_number: asn,
                    autonomous_system_organization: "",
                })?;
                values.insert(asn, data_ref);
                data_ref
            }
        };
        rules.for_each_ip_prefix(|addr, prefix| {
            has_ipv6 |= addr.is_ipv6();
            db.insert_node(IpAddrWithMask::new(addr, prefix), data_ref);
            count += 1;
            Ok(())
        })?;
    }

    if count == 0 {
        bail!("ASN input does not contain any CIDR records");
    }
    set_database_has_ipv6(&mut db, has_ipv6);
    Ok((count, db))
}

pub fn build_asn_mmdb_from_cidrs<I>(entries: I, output: impl AsRef<Path>) -> Result<usize>
where
    I: IntoIterator<Item = (u32, String)>,
{
    let mut db = new_database(
        false,
        "GeoLite2-ASN",
        "ASN database generated by rule-converter",
    );
    let mut values = HashMap::new();
    let mut has_ipv6 = false;
    let mut count = 0usize;

    for (asn, cidr) in entries {
        if asn == 0 {
            bail!("ASN must be greater than 0");
        }
        let parsed = parse_cidr_with_context(&format!("AS{asn}"), &cidr)?;
        has_ipv6 |= parsed.addr.is_ipv6();
        let data_ref = match values.get(&asn) {
            Some(data_ref) => *data_ref,
            None => {
                let data_ref = db.insert_value(AsnRecordValue {
                    autonomous_system_number: asn,
                    autonomous_system_organization: "",
                })?;
                values.insert(asn, data_ref);
                data_ref
            }
        };
        db.insert_node(parsed, data_ref);
        count += 1;
    }

    if count == 0 {
        bail!("ASN input does not contain any CIDR records");
    }
    set_database_has_ipv6(&mut db, has_ipv6);
    write_database(db, output.as_ref())?;
    Ok(count)
}
