use std::collections::HashMap;
use std::path::Path;

use anyhow::{Context, Result, bail};
use maxminddb::{Reader, WithinOptions};
use maxminddb_writer::paths::IpAddrWithMask;

use crate::codec::db::common::{new_database, write_database, write_database_to_memory};

use super::common::{AsnRecordValue, decode_asn};

pub fn convert_asn_mmdb(input: impl AsRef<Path>, output: impl AsRef<Path>) -> Result<usize> {
    let input = input.as_ref();
    let reader = Reader::open_readfile(input)
        .with_context(|| format!("failed to read ASN MMDB {}", input.display()))?;
    let (count, db) = convert_asn_mmdb_reader(reader)?;
    write_database(db, output.as_ref())?;
    Ok(count)
}

pub fn convert_asn_mmdb_to_bytes(input: &[u8]) -> Result<(usize, Vec<u8>)> {
    let reader = Reader::from_source(input).context("failed to read ASN MMDB payload")?;
    let (count, db) = convert_asn_mmdb_reader(reader)?;
    Ok((count, write_database_to_memory(db)?))
}

pub fn convert_asn_mmdb_file_to_bytes(input: impl AsRef<Path>) -> Result<(usize, Vec<u8>)> {
    let input = input.as_ref();
    let reader = Reader::open_readfile(input)
        .with_context(|| format!("failed to read ASN MMDB {}", input.display()))?;
    let (count, db) = convert_asn_mmdb_reader(reader)?;
    Ok((count, write_database_to_memory(db)?))
}

pub(super) fn convert_asn_mmdb_reader<S: AsRef<[u8]>>(
    reader: Reader<S>,
) -> Result<(usize, maxminddb_writer::Database)> {
    let mut db = new_database(
        reader.metadata.ip_version == 6,
        "GeoLite2-ASN",
        "ASN database generated by rule-converter",
    );
    let mut values = HashMap::new();
    let mut count = 0usize;

    for item in reader.networks(WithinOptions::default())? {
        let item = item.context("failed to read ASN MMDB network")?;
        let Some(asn) = decode_asn(&item)? else {
            continue;
        };
        let data_ref = match values.get(&asn) {
            Some(data_ref) => *data_ref,
            None => {
                let data_ref = db.insert_value(AsnRecordValue {
                    autonomous_system_number: asn,
                    autonomous_system_organization: "",
                })?;
                values.insert(asn, data_ref);
                data_ref
            }
        };
        let network = item.network()?;
        db.insert_node(
            IpAddrWithMask::new(network.ip(), network.prefix()),
            data_ref,
        );
        count += 1;
    }

    if count == 0 {
        bail!("ASN input does not contain any ASN records");
    }
    Ok((count, db))
}
