use std::collections::HashMap;
use std::path::Path;

use anyhow::{Result, bail};
use maxminddb_writer::paths::IpAddrWithMask;

use crate::codec::db::common::{
    for_each_cidr, new_database, parse_cidr_with_context, set_database_has_ipv6, write_database,
    write_database_to_memory,
};
use crate::codec::db::format::MmdbFormat;
use crate::codec::db::sing::geoip_database_type;
use crate::codec::mihomo::mrs::RuleSetOutput;
use crate::input::expand_file_paths;

use super::common::{
    CountryCodeValue, CountryRecordValue, country_from_path, normalize_country_code,
};

pub fn build_geoip_mmdb_from_paths<P, I>(
    entries: I,
    output: impl AsRef<Path>,
    format: MmdbFormat,
) -> Result<usize>
where
    P: AsRef<Path>,
    I: IntoIterator<Item = (String, P)>,
{
    let mut db = new_database(
        false,
        geoip_database_type(format),
        "GeoIP country database generated by rule-converter",
    );
    let mut values = HashMap::new();
    let mut has_ipv6 = false;
    let mut count = 0usize;

    for (country, path) in entries {
        let country = normalize_country_code(&country);
        if country.is_empty() {
            bail!("GeoIP country is empty");
        }
        let path = path.as_ref();
        count += for_each_cidr(path, |cidr| {
            has_ipv6 |= cidr.addr.is_ipv6();
            let data_ref = match values.get(&country) {
                Some(data_ref) => *data_ref,
                None => {
                    let data_ref = match format {
                        MmdbFormat::Mmdb => db.insert_value(CountryRecordValue {
                            country: CountryCodeValue { iso_code: &country },
                        })?,
                        MmdbFormat::SingDb | MmdbFormat::MetaDb => {
                            db.insert_value(country.as_str())?
                        }
                        MmdbFormat::Dat | MmdbFormat::SingGeosite => {
                            unreachable!("handled by DB dispatch")
                        }
                    };
                    values.insert(country.clone(), data_ref);
                    data_ref
                }
            };
            db.insert_node(cidr, data_ref);
            Ok(())
        })?;
    }
    if count == 0 {
        bail!("GeoIP input does not contain any CIDR records");
    }
    set_database_has_ipv6(&mut db, has_ipv6);
    write_database(db, output.as_ref())?;
    Ok(count)
}

pub fn build_geoip_mmdb_from_rule_sets<I>(
    entries: I,
    output: impl AsRef<Path>,
    format: MmdbFormat,
) -> Result<usize>
where
    I: IntoIterator<Item = (String, RuleSetOutput)>,
{
    let (count, db) = build_geoip_mmdb_database_from_rule_sets(entries, format)?;
    write_database(db, output.as_ref())?;
    Ok(count)
}

pub fn build_geoip_mmdb_from_rule_sets_to_bytes<I>(
    entries: I,
    format: MmdbFormat,
) -> Result<(usize, Vec<u8>)>
where
    I: IntoIterator<Item = (String, RuleSetOutput)>,
{
    let (count, db) = build_geoip_mmdb_database_from_rule_sets(entries, format)?;
    Ok((count, write_database_to_memory(db)?))
}

pub(super) fn build_geoip_mmdb_database_from_rule_sets<I>(
    entries: I,
    format: MmdbFormat,
) -> Result<(usize, maxminddb_writer::Database)>
where
    I: IntoIterator<Item = (String, RuleSetOutput)>,
{
    let mut db = new_database(
        false,
        geoip_database_type(format),
        "GeoIP country database generated by rule-converter",
    );
    let mut values = HashMap::new();
    let mut has_ipv6 = false;
    let mut count = 0usize;

    for (country, rules) in entries {
        let country = normalize_country_code(&country);
        if country.is_empty() {
            bail!("GeoIP country is empty");
        }
        let data_ref = match values.get(&country) {
            Some(data_ref) => *data_ref,
            None => {
                let data_ref = match format {
                    MmdbFormat::Mmdb => db.insert_value(CountryRecordValue {
                        country: CountryCodeValue { iso_code: &country },
                    })?,
                    MmdbFormat::SingDb | MmdbFormat::MetaDb => db.insert_value(country.as_str())?,
                    MmdbFormat::Dat | MmdbFormat::SingGeosite => {
                        unreachable!("handled by DB dispatch")
                    }
                };
                values.insert(country.clone(), data_ref);
                data_ref
            }
        };
        rules.for_each_ip_prefix(|addr, prefix| {
            has_ipv6 |= addr.is_ipv6();
            db.insert_node(IpAddrWithMask::new(addr, prefix), data_ref);
            count += 1;
            Ok(())
        })?;
    }

    if count == 0 {
        bail!("GeoIP input does not contain any CIDR records");
    }
    set_database_has_ipv6(&mut db, has_ipv6);
    Ok((count, db))
}

pub fn build_geoip_mmdb_from_cidrs<I>(
    entries: I,
    output: impl AsRef<Path>,
    format: MmdbFormat,
) -> Result<usize>
where
    I: IntoIterator<Item = (String, String)>,
{
    let mut db = new_database(
        false,
        geoip_database_type(format),
        "GeoIP country database generated by rule-converter",
    );
    let mut values = HashMap::new();
    let mut has_ipv6 = false;
    let mut count = 0usize;

    for (country, cidr) in entries {
        let country = normalize_country_code(&country);
        if country.is_empty() {
            bail!("GeoIP country is empty");
        }
        let parsed = parse_cidr_with_context(&country, &cidr)?;
        has_ipv6 |= parsed.addr.is_ipv6();
        let data_ref = match values.get(&country) {
            Some(data_ref) => *data_ref,
            None => {
                let data_ref = match format {
                    MmdbFormat::Mmdb => db.insert_value(CountryRecordValue {
                        country: CountryCodeValue { iso_code: &country },
                    })?,
                    MmdbFormat::SingDb | MmdbFormat::MetaDb => db.insert_value(country.as_str())?,
                    MmdbFormat::Dat | MmdbFormat::SingGeosite => {
                        unreachable!("handled by DB dispatch")
                    }
                };
                values.insert(country.clone(), data_ref);
                data_ref
            }
        };
        db.insert_node(parsed, data_ref);
        count += 1;
    }

    if count == 0 {
        bail!("GeoIP input does not contain any CIDR records");
    }
    set_database_has_ipv6(&mut db, has_ipv6);
    write_database(db, output.as_ref())?;
    Ok(count)
}

pub fn build_geoip_mmdb_from_file_names<P, I>(
    paths: I,
    output: impl AsRef<Path>,
    format: MmdbFormat,
) -> Result<usize>
where
    P: AsRef<Path>,
    I: IntoIterator<Item = P>,
{
    let paths = expand_file_paths(paths)?;
    let entries = paths
        .into_iter()
        .map(|path| {
            let country = country_from_path(&path)?;
            Ok((country, path))
        })
        .collect::<Result<Vec<_>>>()?;
    build_geoip_mmdb_from_paths(entries, output, format)
}
