use std::collections::HashMap;
use std::path::Path;

use anyhow::{Context, Result, bail};
use maxminddb::{Reader, WithinOptions};
use maxminddb_writer::paths::IpAddrWithMask;

use crate::codec::db::common::{new_database, write_database, write_database_to_memory};
use crate::codec::db::format::MmdbFormat;
use crate::codec::db::sing::geoip_database_type;

use super::common::{
    CountryCodeValue, CountryRecordValue, decode_first_matching_country_code,
    decode_matching_country_codes, normalize_country_filter,
};

pub fn convert_geoip_mmdb(
    input: impl AsRef<Path>,
    output: impl AsRef<Path>,
    output_format: MmdbFormat,
) -> Result<usize> {
    convert_geoip_mmdb_filtered(input, output, output_format, &[])
}

pub fn convert_geoip_mmdb_filtered(
    input: impl AsRef<Path>,
    output: impl AsRef<Path>,
    output_format: MmdbFormat,
    countries: &[String],
) -> Result<usize> {
    let input = input.as_ref();
    let reader = Reader::open_readfile(input)
        .with_context(|| format!("failed to read GeoIP MMDB {}", input.display()))?;
    let (count, db) = convert_geoip_mmdb_reader(reader, output_format, countries)?;
    write_database(db, output.as_ref())?;
    Ok(count)
}

pub fn convert_geoip_mmdb_to_bytes(
    input: &[u8],
    output_format: MmdbFormat,
) -> Result<(usize, Vec<u8>)> {
    convert_geoip_mmdb_to_bytes_filtered(input, output_format, &[])
}

pub fn convert_geoip_mmdb_to_bytes_filtered(
    input: &[u8],
    output_format: MmdbFormat,
    countries: &[String],
) -> Result<(usize, Vec<u8>)> {
    let reader = Reader::from_source(input).context("failed to read GeoIP MMDB payload")?;
    let (count, db) = convert_geoip_mmdb_reader(reader, output_format, countries)?;
    Ok((count, write_database_to_memory(db)?))
}

pub fn convert_geoip_mmdb_file_to_bytes(
    input: impl AsRef<Path>,
    output_format: MmdbFormat,
) -> Result<(usize, Vec<u8>)> {
    convert_geoip_mmdb_file_to_bytes_filtered(input, output_format, &[])
}

pub fn convert_geoip_mmdb_file_to_bytes_filtered(
    input: impl AsRef<Path>,
    output_format: MmdbFormat,
    countries: &[String],
) -> Result<(usize, Vec<u8>)> {
    let input = input.as_ref();
    let reader = Reader::open_readfile(input)
        .with_context(|| format!("failed to read GeoIP MMDB {}", input.display()))?;
    let (count, db) = convert_geoip_mmdb_reader(reader, output_format, countries)?;
    Ok((count, write_database_to_memory(db)?))
}

pub(super) fn convert_geoip_mmdb_reader<S: AsRef<[u8]>>(
    reader: Reader<S>,
    output_format: MmdbFormat,
    countries: &[String],
) -> Result<(usize, maxminddb_writer::Database)> {
    let mut db = new_database(
        reader.metadata.ip_version == 6,
        geoip_database_type(output_format),
        "GeoIP country database generated by rule-converter",
    );
    let filter = normalize_country_filter(countries);
    let mut count = 0usize;

    match output_format {
        MmdbFormat::Mmdb | MmdbFormat::SingDb => {
            let mut values = HashMap::new();
            for item in reader.networks(WithinOptions::default())? {
                let item = item.context("failed to read GeoIP MMDB network")?;
                let Some(country) = decode_first_matching_country_code(&item, &filter)? else {
                    continue;
                };
                let data_ref = match values.get(&country) {
                    Some(data_ref) => *data_ref,
                    None => {
                        let data_ref = match output_format {
                            MmdbFormat::Mmdb => db.insert_value(CountryRecordValue {
                                country: CountryCodeValue { iso_code: &country },
                            })?,
                            MmdbFormat::SingDb => db.insert_value(country.as_str())?,
                            MmdbFormat::MetaDb | MmdbFormat::Dat | MmdbFormat::SingGeosite => {
                                unreachable!()
                            }
                        };
                        values.insert(country, data_ref);
                        data_ref
                    }
                };
                let network = item.network()?;
                db.insert_node(
                    IpAddrWithMask::new(network.ip(), network.prefix()),
                    data_ref,
                );
                count += 1;
            }
        }
        MmdbFormat::Dat | MmdbFormat::SingGeosite => unreachable!("handled by DB dispatch"),
        MmdbFormat::MetaDb => {
            let mut values = HashMap::new();
            for item in reader.networks(WithinOptions::default())? {
                let item = item.context("failed to read GeoIP MMDB network")?;
                let countries = decode_matching_country_codes(&item, &filter)?;
                if countries.is_empty() {
                    continue;
                }
                let data_ref = match values.get(&countries) {
                    Some(data_ref) => *data_ref,
                    None => {
                        let data_ref = if countries.len() == 1 {
                            db.insert_value(countries[0].as_str())?
                        } else {
                            db.insert_value(&countries)?
                        };
                        values.insert(countries, data_ref);
                        data_ref
                    }
                };
                let network = item.network()?;
                db.insert_node(
                    IpAddrWithMask::new(network.ip(), network.prefix()),
                    data_ref,
                );
                count += 1;
            }
        }
    }

    if count == 0 {
        bail!("GeoIP input does not contain any country records");
    }
    Ok((count, db))
}
